export const REGISTER_ACTION = '[actions] register'
export const LOGIN_ACTION = '[actions] login'
export const SET_USER_TOKEN_DATA_MUTATION = '[mutations] set user token data'
export const GET_USER_TOKEN_DATA_GETTER = '[getters] get user token data'
export const SET_LOADING_MUTATION = '[mutations] set loading'